# Generated by Django 5.0.2 on 2024-02-14 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricing',
            unique_together=set(),
        ),
    ]
