# Generated by Django 5.0.2 on 2024-02-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_system', '0002_alter_pricing_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricing',
            unique_together={('organization', 'item', 'zone')},
        ),
    ]
